### ISSUE TITLE
Figure out how to load packages from github

### ISSUE THREAD

**Issue by robertzk** [robertzk/syberia#39]
Some sort of dependency manager or install script?

**Comment by kirillseva** [comment]
https://github.com/avantcredit/avant-analytics/blob/master/config/lockfile.yml

something along those lines? Let people specify repo (and ref, default ref===master), if repo is not specified - take from CRAN. If cran doesn't have it - :cry:

**Comment by robertzk** [comment]
Partially solved by [lockbox](https://github.com/robertzk/lockbox).
